create table blackList(
  _id integer primary key autoincrement,
  contactId integer not null,
  contactName text not null);

create table feast (
  _id integer primary key autoincrement,
  day char(5) not null,
  name varchar(64) not null,
  lastWishYear char(4) null);

create index idx_feast_day on feast (day);
create index idx_feast_name on feast (name);

insert into feast (name, day) values ('Maria', '01/01');
insert into feast (name, day) values ('Télémaque', '01/01');
insert into feast (name, day) values ('Basile','02/01');
insert into feast (name, day) values ('Geneviève', '03/01');
insert into feast (name, day) values ('Odilon', '04/01');
insert into feast (name, day) values ('Edouard', '05/01');
insert into feast (name, day) values ('Mélaine', '06/01');
insert into feast (name, day) values ('Raymond', '07/01');
insert into feast (name, day) values ('Lucien', '08/01');
insert into feast (name, day) values ('Alix', '09/01');
insert into feast (name, day) values ('Guillaume', '10/01');
insert into feast (name, day) values ('Paulin', '11/01');
insert into feast (name, day) values ('Tatiana', '12/01');
insert into feast (name, day) values ('Yvette', '13/01');
insert into feast (name, day) values ('Nina', '14/01');
insert into feast (name, day) values ('Rémi', '15/01');
insert into feast (name, day) values ('Marcel', '16/01');
insert into feast (name, day) values ('Roseline', '17/01');
insert into feast (name, day) values ('Prisca', '18/01');
insert into feast (name, day) values ('Marius', '19/01');
insert into feast (name, day) values ('Sébastien', '20/01');
insert into feast (name, day) values ('Agnès', '21/01');
insert into feast (name, day) values ('Vincent', '22/01');
insert into feast (name, day) values ('Barnard', '23/01');
insert into feast (name, day) values ('Fr. de Sales', '24/01');
insert into feast (name, day) values ('Conv. de St Paul', '25/01');
insert into feast (name, day) values ('Paule', '26/01');
insert into feast (name, day) values ('Angèle', '27/01');
insert into feast (name, day) values ("Thomas d'Aquin", '28/01');
insert into feast (name, day) values ('Gildas', '29/01');
insert into feast (name, day) values ('Martine', '30/01');
insert into feast (name, day) values ('Marcelle', '31/01');
insert into feast (name, day) values ('Ella', '01/02');
insert into feast (name, day) values ('Présentation', '02/02');
insert into feast (name, day) values ('Blaise', '03/02');
insert into feast (name, day) values ('Véronique', '04/02');
insert into feast (name, day) values ('Agathe', '05/02');
insert into feast (name, day) values ('Gaston', '06/02');
insert into feast (name, day) values ('Eugénie', '07/02');
insert into feast (name, day) values ('Jaqueline', '08/02');
insert into feast (name, day) values ('Apolline', '09/02');
insert into feast (name, day) values ('Arnaud', '10/02');
insert into feast (name, day) values ('ND de Lourdes', '11/02');
insert into feast (name, day) values ('Félix', '12/02');
insert into feast (name, day) values ('Béatrice', '13/02');
insert into feast (name, day) values ('Valentin', '14/02');
insert into feast (name, day) values ('Claude', '15/02');
insert into feast (name, day) values ('Julienne', '16/02');
insert into feast (name, day) values ('Alexis', '17/02');
insert into feast (name, day) values ('Bernadette', '18/02');
insert into feast (name, day) values ('Gabin', '19/02');
insert into feast (name, day) values ('Aimée', '20/02');
insert into feast (name, day) values ('Pierre-Damien', '21/02');
insert into feast (name, day) values ('Isabelle', '22/02');
insert into feast (name, day) values ('Lazare', '23/02');
insert into feast (name, day) values ('Modeste', '24/02');
insert into feast (name, day) values ('Roméo', '25/02');
insert into feast (name, day) values ('Nestor', '26/02');
insert into feast (name, day) values ('Honorine', '27/02');
insert into feast (name, day) values ('Romain', '28/02');
insert into feast (name, day) values ('Aubin', '01/03');
insert into feast (name, day) values ('Ch. Le Bon', '02/03');
insert into feast (name, day) values ('Gwenolé', '03/03');
insert into feast (name, day) values ('Casimir', '04/03');
insert into feast (name, day) values ('Olive', '05/03');
insert into feast (name, day) values ('Colette', '06/03');
insert into feast (name, day) values ('Félicité', '07/03');
insert into feast (name, day) values ('Jean De Dieu', '08/03');
insert into feast (name, day) values ('Françoise', '09/03');
insert into feast (name, day) values ('Vivien', '10/03');
insert into feast (name, day) values ('Rosine', '11/03');
insert into feast (name, day) values ('Justine', '12/03');
insert into feast (name, day) values ('Rodrigue', '13/03');
insert into feast (name, day) values ('Mathilde', '14/03');
insert into feast (name, day) values ('Louise', '15/03');
insert into feast (name, day) values ('Bénédicte', '16/03');
insert into feast (name, day) values ('Patrick', '17/03');
insert into feast (name, day) values ('Cyrille', '18/03');
insert into feast (name, day) values ('Joseph', '19/03');
insert into feast (name, day) values ('PRINTEMPS', '20/03');
insert into feast (name, day) values ('Clémence', '21/03');
insert into feast (name, day) values ('Léa', '22/03');
insert into feast (name, day) values ('Victorien', '23/03');
insert into feast (name, day) values ('Cath. De Suède', '24/03');
insert into feast (name, day) values ('Humbert', '25/03');
insert into feast (name, day) values ('Larissa', '26/03');
insert into feast (name, day) values ('Habib', '27/03');
insert into feast (name, day) values ('Gontran', '28/03');
insert into feast (name, day) values ('Gwladys', '29/03');
insert into feast (name, day) values ('Amédée', '30/03');
insert into feast (name, day) values ('Benjamin', '31/03');
insert into feast (name, day) values ('Hugues', '01/04');
insert into feast (name, day) values ('Sandrine', '02/04');
insert into feast (name, day) values ('Richard', '03/04');
insert into feast (name, day) values ('Isidore', '04/04');
insert into feast (name, day) values ('Irène', '05/04');
insert into feast (name, day) values ('Marcellin', '06/04');
insert into feast (name, day) values ('J.B. de la Sal', '07/04');
insert into feast (name, day) values ('Julie', '08/04');
insert into feast (name, day) values ('Gautier', '09/04');
insert into feast (name, day) values ('Fulbert', '10/04');
insert into feast (name, day) values ('Stanislas', '11/04');
insert into feast (name, day) values ('Jules', '12/04');
insert into feast (name, day) values ('Ida', '13/04');
insert into feast (name, day) values ('Maxime', '14/04');
insert into feast (name, day) values ('Paterne', '15/04');
insert into feast (name, day) values ('Benoît-Joseph', '16/04');
insert into feast (name, day) values ('Anicet', '17/04');
insert into feast (name, day) values ('Parfait', '18/04');
insert into feast (name, day) values ('Emma', '19/04');
insert into feast (name, day) values ('Odette', '20/04');
insert into feast (name, day) values ('Anselme', '21/04');
insert into feast (name, day) values ('Alexandre', '22/04');
insert into feast (name, day) values ('Georges', '23/04');
insert into feast (name, day) values ('fidèle', '24/04');
insert into feast (name, day) values ('Marc', '25/04');
insert into feast (name, day) values ('Alida', '26/04');
insert into feast (name, day) values ('Zita', '27/04');
insert into feast (name, day) values ('Valérie', '28/04');
insert into feast (name, day) values ('Cath. de Sien', '29/04');
insert into feast (name, day) values ('Robert', '30/04');
insert into feast (name, day) values ('FETE DU TRAVAIL', '01/05');
insert into feast (name, day) values ('Boris', '02/05');
insert into feast (name, day) values ('Philippe/Jacques', '03/05');
insert into feast (name, day) values ('Sylvain', '04/05');
insert into feast (name, day) values ('Judith', '05/05');
insert into feast (name, day) values ('Prudence', '06/05');
insert into feast (name, day) values ('Gisèle', '07/05');
insert into feast (name, day) values ('VICTOIRE 1945', '08/05');
insert into feast (name, day) values ('Pacôme', '09/05');
insert into feast (name, day) values ('Solange', '10/05');
insert into feast (name, day) values ('Estelle', '11/05');
insert into feast (name, day) values ('Achille', '12/05');
insert into feast (name, day) values ('Rolande', '13/05');
insert into feast (name, day) values ('Matthias', '14/05');
insert into feast (name, day) values ('Denise', '15/05');
insert into feast (name, day) values ('Honoré', '16/05');
insert into feast (name, day) values ('Pascal', '17/05');
insert into feast (name, day) values ('Eric', '18/05');
insert into feast (name, day) values ('Yves', '19/05');
insert into feast (name, day) values ('Bernardin', '20/05');
insert into feast (name, day) values ('Constantin', '21/05');
insert into feast (name, day) values ('Emile', '22/05');
insert into feast (name, day) values ('Didier', '23/05');
insert into feast (name, day) values ('Donatien', '24/05');
insert into feast (name, day) values ('Sophie', '25/05');
insert into feast (name, day) values ('Bérenger', '26/05');
insert into feast (name, day) values ('Augustin', '27/05');
insert into feast (name, day) values ('Germain', '28/05');
insert into feast (name, day) values ('Aymard', '29/05');
insert into feast (name, day) values ('Ferdinand', '30/05');
insert into feast (name, day) values ('VISITATION', '31/05');
insert into feast (name, day) values ('Justin', '01/06');
insert into feast (name, day) values ('Blandine', '02/06');
insert into feast (name, day) values ('Kévin', '03/06');
insert into feast (name, day) values ('Clotilde', '04/06');
insert into feast (name, day) values ('Igor', '05/06');
insert into feast (name, day) values ('Norbert', '06/06');
insert into feast (name, day) values ('Gilbert', '07/06');
insert into feast (name, day) values ('Médard', '08/06');
insert into feast (name, day) values ('Diane', '09/06');
insert into feast (name, day) values ('Landry', '10/06');
insert into feast (name, day) values ('Barnabé', '11/06');
insert into feast (name, day) values ('Guy', '12/06');
insert into feast (name, day) values ('Ant. de Padoue', '13/06');
insert into feast (name, day) values ('Elisée', '14/06');
insert into feast (name, day) values ('Germaine', '15/06');
insert into feast (name, day) values ('JF Régis', '16/06');
insert into feast (name, day) values ('Hervé', '17/06');
insert into feast (name, day) values ('Léonce', '18/06');
insert into feast (name, day) values ('Romuald', '19/06');
insert into feast (name, day) values ('Silvère', '20/06');
insert into feast (name, day) values ('ETE', '21/06');
insert into feast (name, day) values ('Alban', '22/06');
insert into feast (name, day) values ('Audrey', '23/06');
insert into feast (name, day) values ('J.Batiste', '24/06');
insert into feast (name, day) values ('Prosper', '25/06');
insert into feast (name, day) values ('Anthelme', '26/06');
insert into feast (name, day) values ('Fernand', '27/06');
insert into feast (name, day) values ('Irénée', '28/06');
insert into feast (name, day) values ('Pierre/Paul', '29/06');
insert into feast (name, day) values ('Martial', '30/06');
insert into feast (name, day) values ('Thierry', '01/07');
insert into feast (name, day) values ('Martinien', '02/07');
insert into feast (name, day) values ('Thomas', '03/07');
insert into feast (name, day) values ('Florent', '04/07');
insert into feast (name, day) values ('Antoine', '05/07');
insert into feast (name, day) values ('Mariette', '06/07');
insert into feast (name, day) values ('Raoul', '07/07');
insert into feast (name, day) values ('Thibaut', '08/07');
insert into feast (name, day) values ('Amandine', '09/07');
insert into feast (name, day) values ('Ulrich', '10/07');
insert into feast (name, day) values ('Benoît', '11/07');
insert into feast (name, day) values ('Olivier', '12/07');
insert into feast (name, day) values ('Henri/Joël', '13/07');
insert into feast (name, day) values ('FETE NATIONALE', '14/07');
insert into feast (name, day) values ('Donald', '15/07');
insert into feast (name, day) values ('ND du Mt Carmel', '16/07');
insert into feast (name, day) values ('Charlotte', '17/07');
insert into feast (name, day) values ('Frédéric', '18/07');
insert into feast (name, day) values ('Arsène', '19/07');
insert into feast (name, day) values ('Marina', '20/07');
insert into feast (name, day) values ('Victor', '21/07');
insert into feast (name, day) values ('Marie-Madeleine', '22/07');
insert into feast (name, day) values ('Brigitte', '23/07');
insert into feast (name, day) values ('Christine', '24/07');
insert into feast (name, day) values ('Jacques', '25/07');
insert into feast (name, day) values ('Anne/Joachim', '26/07');
insert into feast (name, day) values ('Nathalie', '27/07');
insert into feast (name, day) values ('Samson', '28/07');
insert into feast (name, day) values ('Marthe', '29/07');
insert into feast (name, day) values ('Juliette', '30/07');
insert into feast (name, day) values ('Ignace de L.', '31/07');
insert into feast (name, day) values ('Alphonse', '01/08');
insert into feast (name, day) values ('Julien Eymard', '02/08');
insert into feast (name, day) values ('Lydie', '03/08');
insert into feast (name, day) values ('JM Vianney', '04/08');
insert into feast (name, day) values ('Abel', '05/08');
insert into feast (name, day) values ('TRANSFIGURATION', '06/08');
insert into feast (name, day) values ('Gaétan', '07/08');
insert into feast (name, day) values ('Dominique', '08/08');
insert into feast (name, day) values ('Amour', '09/08');
insert into feast (name, day) values ('Laurent', '10/08');
insert into feast (name, day) values ('Claire', '11/08');
insert into feast (name, day) values ('Clarisse', '12/08');
insert into feast (name, day) values ('Hippolyte', '13/08');
insert into feast (name, day) values ('Evrard', '14/08');
insert into feast (name, day) values ('ASSOMPTION', '15/08');
insert into feast (name, day) values ('Armel', '16/08');
insert into feast (name, day) values ('Hyacinthe', '17/08');
insert into feast (name, day) values ('Hélène', '18/08');
insert into feast (name, day) values ('Jean Eudes', '19/08');
insert into feast (name, day) values ('Bernard', '20/08');
insert into feast (name, day) values ('Christophe', '21/08');
insert into feast (name, day) values ('Fabrice', '22/08');
insert into feast (name, day) values ('Rose de L.', '23/08');
insert into feast (name, day) values ('Barthélemy', '24/08');
insert into feast (name, day) values ('Louis', '25/08');
insert into feast (name, day) values ('Natacha', '26/08');
insert into feast (name, day) values ('Monique', '27/08');
insert into feast (name, day) values ('Augustin', '28/08');
insert into feast (name, day) values ('Sabine', '29/08');
insert into feast (name, day) values ('Fiacre', '30/08');
insert into feast (name, day) values ('Aristide', '31/08');
insert into feast (name, day) values ('Gilles', '01/09');
insert into feast (name, day) values ('Ingrid', '02/09');
insert into feast (name, day) values ('Grégoire', '03/09');
insert into feast (name, day) values ('Rosalie', '04/09');
insert into feast (name, day) values ('Raïssa', '05/09');
insert into feast (name, day) values ('Bertrand', '06/09');
insert into feast (name, day) values ('Reine', '07/09');
insert into feast (name, day) values ('NATIVITE DE ND', '08/09');
insert into feast (name, day) values ('Alain', '09/09');
insert into feast (name, day) values ('Inès', '10/09');
insert into feast (name, day) values ('Adelphe', '11/09');
insert into feast (name, day) values ('Apollinaire', '12/09');
insert into feast (name, day) values ('Aimé', '13/09');
insert into feast (name, day) values ('LA Ste CROIX', '14/09');
insert into feast (name, day) values ('Roland', '15/09');
insert into feast (name, day) values ('Edith', '16/09');
insert into feast (name, day) values ('Renaud', '17/09');
insert into feast (name, day) values ('Nadège', '18/09');
insert into feast (name, day) values ('Emilie', '19/09');
insert into feast (name, day) values ('Davy', '20/09');
insert into feast (name, day) values ('Matthieu', '21/09');
insert into feast (name, day) values ('Maurice', '22/09');
insert into feast (name, day) values ('AUTOMNE', '23/09');
insert into feast (name, day) values ('Thècle', '24/09');
insert into feast (name, day) values ('Hermann', '25/09');
insert into feast (name, day) values ('Côme/Damien', '26/09');
insert into feast (name, day) values ('Vincent de Pau', '27/09');
insert into feast (name, day) values ('Venceslas', '28/09');
insert into feast (name, day) values ('Michel/Gabriel', '29/09');
insert into feast (name, day) values ('Jérôme', '30/09');
insert into feast (name, day) values ("Th. de l'E. J", '01/10');
insert into feast (name, day) values ('Léger', '02/10');
insert into feast (name, day) values ('Gérard', '03/10');
insert into feast (name, day) values ("Fr. d'Assise", '04/10');
insert into feast (name, day) values ('Fleur', '05/10');
insert into feast (name, day) values ('Bruno', '06/10');
insert into feast (name, day) values ('Serge', '07/10');
insert into feast (name, day) values ('Pélagie', '08/10');
insert into feast (name, day) values ('Denis', '09/10');
insert into feast (name, day) values ('Ghislain', '10/10');
insert into feast (name, day) values ('Firmin', '11/10');
insert into feast (name, day) values ('Wilfrid', '12/10');
insert into feast (name, day) values ('Géraud', '13/10');
insert into feast (name, day) values ('Juste', '14/10');
insert into feast (name, day) values ("Th. d'Avila", '15/10');
insert into feast (name, day) values ('Edwige', '16/10');
insert into feast (name, day) values ('Baudouin', '17/10');
insert into feast (name, day) values ('Luc', '18/10');
insert into feast (name, day) values ('René', '19/10');
insert into feast (name, day) values ('Adeline', '20/10');
insert into feast (name, day) values ('Céline', '21/10');
insert into feast (name, day) values ('Elodie', '22/10');
insert into feast (name, day) values ('J. de Capistan', '23/10');
insert into feast (name, day) values ('Florentin', '24/10');
insert into feast (name, day) values ('Crespin', '25/10');
insert into feast (name, day) values ('Dimitri', '26/10');
insert into feast (name, day) values ('Emeline', '27/10');
insert into feast (name, day) values ('Simon/Jude', '28/10');
insert into feast (name, day) values ('Narcisse', '29/10');
insert into feast (name, day) values ('Bienvenue', '30/10');
insert into feast (name, day) values ('Quentin', '31/10');
insert into feast (name, day) values ('TOUSSAINT', '01/11');
insert into feast (name, day) values ('JOUR DES DEFUNTS', '02/11');
insert into feast (name, day) values ('Hubert', '03/11');
insert into feast (name, day) values ('Charles', '04/11');
insert into feast (name, day) values ('Sylvie', '05/11');
insert into feast (name, day) values ('Bertille', '06/11');
insert into feast (name, day) values ('Carine', '07/11');
insert into feast (name, day) values ('Geoffroy', '08/11');
insert into feast (name, day) values ('Théodore', '09/11');
insert into feast (name, day) values ('Léon', '10/11');
insert into feast (name, day) values ('ARMISTICE 1918', '11/11');
insert into feast (name, day) values ('Christian', '12/11');
insert into feast (name, day) values ('Brice', '13/11');
insert into feast (name, day) values ('Sidoine', '14/11');
insert into feast (name, day) values ('Albert', '15/11');
insert into feast (name, day) values ('Marguerite', '16/11');
insert into feast (name, day) values ('Elisabeth', '17/11');
insert into feast (name, day) values ('Aude', '18/11');
insert into feast (name, day) values ('Tanguy', '19/11');
insert into feast (name, day) values ('Edmond', '20/11');
insert into feast (name, day) values ('Prés. Marie', '21/11');
insert into feast (name, day) values ('Cécile', '22/11');
insert into feast (name, day) values ('Clément', '23/11');
insert into feast (name, day) values ('Christ Roi', '24/11');
insert into feast (name, day) values ('Catherine', '25/11');
insert into feast (name, day) values ('Delphine', '26/11');
insert into feast (name, day) values ('Séverin', '27/11');
insert into feast (name, day) values ('J. de la March', '28/11');
insert into feast (name, day) values ('Saturnin', '29/11');
insert into feast (name, day) values ('André', '30/11');
insert into feast (name, day) values ('Florence', '01/12');
insert into feast (name, day) values ('Viviane', '02/12');
insert into feast (name, day) values ('François Xavier', '03/12');
insert into feast (name, day) values ('Barbara', '04/12');
insert into feast (name, day) values ('Gérald', '05/12');
insert into feast (name, day) values ('Nicolas', '06/12');
insert into feast (name, day) values ('Ambroise', '07/12');
insert into feast (name, day) values ('Elfried', '08/12');
insert into feast (name, day) values ('Imm. Conception', '09/12');
insert into feast (name, day) values ('Romaric', '10/12');
insert into feast (name, day) values ('Daniel', '11/12');
insert into feast (name, day) values ('JF de Chantal', '12/12');
insert into feast (name, day) values ('Lucie', '13/12');
insert into feast (name, day) values ('Odile', '14/12');
insert into feast (name, day) values ('Ninon', '15/12');
insert into feast (name, day) values ('Alice', '16/12');
insert into feast (name, day) values ('Gaël', '17/12');
insert into feast (name, day) values ('Gatien', '18/12');
insert into feast (name, day) values ('Urbain', '19/12');
insert into feast (name, day) values ('Théophile', '20/12');
insert into feast (name, day) values ('P. Canisius', '21/12');
insert into feast (name, day) values ('HIVER', '22/12');
insert into feast (name, day) values ('Armand', '23/12');
insert into feast (name, day) values ('Adèle', '24/12');
insert into feast (name, day) values ('NOEL', '25/12');
insert into feast (name, day) values ('Etienne', '26/12');
insert into feast (name, day) values ("Jean l'Evangeliste", '27/12');
insert into feast (name, day) values ('Innocents', '28/12');
insert into feast (name, day) values ('Famille', '29/12');
insert into feast (name, day) values ('Roger', '30/12');
insert into feast (name, day) values ('Sylvestre', '31/12');
insert into feast (name, day) values ('Auguste, Augusta', '29/02');